config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :doctors
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  authenticated :doctor do
    root to: 'doctors#show', as: :authenticated_doctor
  end
  
  authenticated :user do
    root to: 'doctors#index', as: :authenticated_user
  end
  
  unauthenticated do
    root 'pages#home'
  end

  resources :users, only: [ :new, :create, :index, :show ] do 
    resources :appointments, only: [ :new, :create ]
  end

  resources :recommendations, only: [ :show ]
  
  resources :doctors, only: [ :new, :create, :index, :show ] do 
    resources :appointments, only: [ :edit, :update ] do
      resources :recommendations, only: [ :new, :create ]
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class DoctorsAppointmentsValidator < ActiveModel::Validator
  def validate(appointment)
    return if appointment.doctor == nil
    if appointment.doctor.appointments.where(open: true).count > 10
      appointment.errors.add :doctor, "This doctor has 10 appointments"
    end
  end
end

class Appointment < ApplicationRecord
  include ActiveModel::Validations

  belongs_to :user
  belongs_to :doctor
  has_one :recommendation

  validates :user, presence: true
  validates :doctor, presence: true
  validates_with DoctorsAppointmentsValidator
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, uniqueness: true
    has_many :doctors
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments
  has_many :users, through: :appointments
  has_one_attached :avatar
  
  belongs_to :category, optional: true
  
  validates :phone_no, presence: true
  validates :phone_no, uniqueness: true
  validates :phone_no, format: { with: /^(\+\d{1,3}\s?)?1?\-?\.?\s?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$/, multiline: true }

  def available?
    self.appointments.count < 10
  end
  
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :appointment
  validates :appointment, presence: true

    after_save :close_appointment
    def close_appointment
      self.appointment.update(open: false)
    end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :email_confirmation, :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:phone_no]
        
  has_many :appointments
  has_many :doctors, through: :appointments
  
  validates :phone_no, uniqueness: true
  validates :phone_no, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      added_attrs = [:phone_no, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @doctor = Doctor.find(params[:doctor_id])
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.user = current_user
    redirect_to "/"
  end

  def edit
  end

  def update
  end

  private

  def appointment_params
    params.require(:appointment).permit(:doctor_id, :date)
  end
  
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!, only: [ :index ]
  before_action :authenticate_doctor!, only: [ :show ]

  def show
    @doctor = current_doctor
    @future_appointments = @doctor.appointments.where("date > ?", Time.now)
    @past_appointments = @doctor.appointments.where("date < ?", Time.now).order(:date)
  end

  def new
  end
  
  def create
  end

  def index
    @categories = Category.all
    if params[:query].present?
      @doctors = Doctor.where(category_id: params[:query])
    else
      @doctors = Doctor.all
    end
    @user = current_user
  end


  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :authenticate_user!, only: [ :show ]
  before_action :authenticate_doctor!, only: [ :new, :create ]

  

  def new
    @recommendation = Recommendation.new
    @appointment = Appointment.find(params[:appointment_id])
    @doctor = @appointment.doctor
    @user = @appointment.user
  end
  
  def create
    @recommendation = Recommendation.new(recommendation_params)
    @recommendation.appointment = Appointment.find(params[:appointment_id])
    @recommendation.save!
    redirect_to current_doctor
  end

  def show
    @recommendation = Recommendation.find(params[:id])
  end

  private

  def recommendation_params
    params.require(:recommendation).permit(:comment)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
  end

  def index
  end

  def show
    @user = User.find(params[:id])
    @appointments = @user.appointments.order(open: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/create.html.erb
<h1>Appointments#create</h1>
<p>Find me in app/views/appointments/create.html.erb</p>

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<p>Find me in app/views/appointments/new.html.erb</p>

<%= simple_form_for [ current_user, @appointment ] do |f| %>
    <%= f.hidden_field :doctor_id, value: @doctor.id %>
    <%= f.input :date %>
    <%= f.submit %>
<% end %>

app/views/appointments/update.html.erb
<h1>Appointments#update</h1>
<p>Find me in app/views/appointments/update.html.erb</p>

app/views/doctors/create.html.erb
<h1>Doctors#create</h1>
<p>Find me in app/views/doctors/create.html.erb</p>

app/views/doctors/index.html.erb
<h1>Doctors#index</h1>
<p>Find me in app/views/doctors/index.html.erb</p>
<hr>

<%= form_tag doctors_path, method: :get do %>
  <%= select_tag :query, 
    options_from_collection_for_select(@categories, "id", "name") %>
  <%= submit_tag "Search" %>
<% end %>


<% @doctors.each do |doctor| %>
      <p>
        <%= cl_image_tag doctor.avatar.key, gravity: :face, height: 50 , width: 50, crop: :fill if doctor.avatar.attached? %>
        <%= doctor.first_name %> <%= doctor.last_name %>
        <%= doctor.category.name if doctor.category.present? %> 
        | <%= link_to 'Create appointment', new_user_appointment_path( current_user, doctor_id: doctor ) if doctor.available? %>
    </p>
<% end %>
<hr>

app/views/doctors/new.html.erb
<h1>Doctors#new</h1>
<p>Find me in app/views/doctors/new.html.erb</p>

app/views/doctors/show.html.erb
<h1>Doctors#show</h1>
<p>
    Hello, 
    <%= @doctor.first_name %>
    <%= @doctor.last_name %>
    <%= @doctor.category.name if @doctor.category.present? %>
</p>
<p>
    <%= @doctor.email %>
</p>
<h1>Upcoming appointments:</h1>
<% @future_appointments.each do |appointment| %>
    <p>
        <%= appointment.user.first_name %> 
        <%= appointment.user.last_name %>
        | 
        <%= appointment.date.strftime("%a %b %d %Y") %>

    </p>
<% end %>
<hr>
<h1>Past appointments:</h1>
<% @past_appointments.each do |appointment| %>
    <p>
        <%= appointment.user.first_name %> 
        <%= appointment.user.last_name %>
        | 
        <%= appointment.date.strftime("%a %b %d %Y") %>
        | 
        <% if appointment.recommendation.present? %>
            <%= link_to "Read the recommendation", appointment.recommendation %>
        <% else %>    
            <%= link_to "Write a recommendation", new_doctor_appointment_recommendation_path(@doctor, appointment) %>
        <% end %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCodicaTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
    <%= render 'shared/navbar' %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h4>
    <%= link_to "I am a doctor", new_doctor_session_path %>
</h4>

<h4>
    <%= link_to "I am a patient", new_user_session_path %>
</h4>

app/views/recommendations/create.html.erb
<h1>Recommendations#create</h1>
<p>Find me in app/views/recommendations/create.html.erb</p>

app/views/recommendations/new.html.erb
<h1>Recommendations#new</h1>
<p>Find me in app/views/recommendations/new.html.erb</p>
<h1>
    Recommendation for 
    <%= @user.first_name %>
    <%= @user.last_name %>:
</h1>
<%= simple_form_for [ @doctor, @appointment, @recommendation ] do |f| %>
    <%= f.text_area :comment, as: :text, size: "50x10" %>
    <%= f.button :submit %>
<% end %>

app/views/recommendations/show.html.erb
<h1>Recommendations#show</h1>
<p>Find me in app/views/recommendations/show.html.erb</p>
<p><%= @recommendation.comment %></p>

app/views/shared/_navbar.html.erb
<hr>
<% if user_signed_in? %>
    <% user = (current_user || current_doctor)%>
    <%= link_to "Log out", destroy_user_session_path, method: :delete %> |
    <%= link_to "Profile", user_path(user) %> |
    <%= user.first_name %>
    <%= user.last_name %>
<% else %>
    <%= link_to "Doctor or user", destroy_user_session_path, method: :delete %> |
    <%= link_to 'Login', new_user_session_path %>
<% end %>
<hr>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= link_to 'Back', doctors_path %>
<p><%= @user.email %></p>
<h1>Hello <%= "#{@user.first_name} #{@user.last_name}" %></h1>
<p></p>
<% @appointments.each do |appointment| %>
    <p>
        <%= appointment.doctor.category.name %> | 
        <%= appointment.doctor.first_name %>
        <%= appointment.doctor.last_name %>
        <%= appointment.date.strftime("%a %b %d %Y") %>
        <% if !appointment.open %>
            | <%= link_to "Read recommendation", recommendation_path(appointment.recommendation) %> 
        <% end %>
    </p>
<% end %>